### PR TITLE
fix: change support url

### PR DESCRIPTION
**Pull request by shawaj**
update support url

**Issue**

- Link:
- Summary:

**How**

**Screenshots**

**References**

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Comment by Ryan-Goldstein** [comment]
Hey @shawaj, you just changed the visible link, but not the actual URL!

**Comment by shawaj** [comment]
@Ryan-Goldstein lol - this is why you shouldnt code at 3am :-P

**Comment by shawaj** [comment]
Fixed now thanks @Ryan-Goldstein

**Comment by Ryan-Goldstein** [comment]
The magic of open source - the entire world can look over your shoulder and point out your mistakes. 😄

**Comment by shawaj** [comment]
> The magic of open source - the entire world can look over your shoulder and point out your mistakes. 😄

Love it :-P

**Review by MuratUrsavas — APPROVED** [review]

**Pull request merged**
