### PR TITLE
Convert to Flask App

### PR DESCRIPTION
**Pull request by robputt**

### CODE REVIEW

**Comment by robputt** [comment]
https://github.com/NebraLtd/hm-diag/issues/60

**Comment by vpetersson** [comment]
Minor comment but can we make sure to use the environment variable `DEBUG=1|0` to toggle debug logging. That way we can easily bump it up on an individual device in Balena.

**Comment by robputt** [comment]
> Minor comment but can we make sure to use the environment variable `DEBUG=1|0` to toggle debug logging. That way we can easily bump it up on an individual device in Balena.

Fixed here - https://github.com/NebraLtd/hm-diag/pull/81/files#diff-c0db576c8a0baae584728f93e68fd6f8bd10013bd6b9af4045ef9b8cd47b9d0cR11

**Comment by robputt** [comment]
Fixing https://github.com/NebraLtd/hm-diag/issues/86 in here too as its a blocker for release.

**Comment by marvinmarnold** [comment]
@robputt thanks for pushing this out. I'm doing some basic reading about the Flash framework before diving into your code. In the meantime, it would be helpful if you could rebase this PR into a smaller number of commits. Some specific requests:

- Remove merge commits from history. Rebase on top of master instead of merging in. I'm not clear why the [two](https://github.com/NebraLtd/hm-diag/pull/81/commits/22984ab3456728a83140786a9d7edee118479602) [other](https://github.com/NebraLtd/hm-diag/pull/81/commits/68411bc823dcb463c0d07387c84a3986b2d2603c) merge commits were necessary. Rebase or cherry-pick instead.
- Add additional context to the commit messages. For example I shouldn't have to look at the code to understand what's happening in `Fix up bluetooth and lte detection` at a more granular level.
- Rebase/squash into a smaller number of commits.

**Comment by robputt** [comment]
Re-opened as https://github.com/NebraLtd/hm-diag/pull/92 with squash & rebase.

**Pull request closed without merging**
