### PR TITLE
Fix slow responses issue by switching to port 7000

### PR DESCRIPTION
**Pull request by kashifpk**
See the original discussion in #248 .

Basically using a different port instead of the current 5000  for gunicorn solves the issue.

Merging of this PR should be done in parallel with:  https://github.com/NebraLtd/helium-miner-software/pull/276

### CODE REVIEW

**Comment by kashifpk** [comment]
Update on this. Moving my Pi to @marvinmarnold's dev-nebra fleet updated it with the image he had running on it (which was also from latest master) and there were not delays there. So we haven't been able to pin-point the cause of this issue. Also this issue isn't appearing on actual miner.

I'll keep monitoring testnet for this as we did just push `/version` endpiont related code to master so it should be in testnet. If this appears in testnet then we should investigate further. Otherwise if it's not happening on the miners then it's probably not worth the time for investigation.

**Comment by vpetersson** [comment]
I don't want to merge this until we have seen some hard evidence for this (e.g. the tests) and/or understand *why* changing port fixes this issue.

**Comment by kashifpk** [comment]
> I don't want to merge this until we have seen some hard evidence for this (e.g. the tests) and/or understand _why_ changing port fixes this issue.

I agree.  I'll convert it to draft for the time being and later either close it or make appropriate changes if we see this issue in testnet.

**Comment by robputt** [comment]
I would suggest closing this, not sure it makes sense.

**Comment by shawaj** [comment]
Quite an old one that's been abandoned and don't think we found this to be an issue in the end

**Comment by kashifpk** [comment]
Yes we never experienced it on our production miners.

**Pull request closed without merging**
