### PR TITLE
feat: clarify radio false when no location assert

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link: #398 
- Summary: clarify radio false when no location assert

**How**

clarify radio false when no location assert

**Screenshots**

**References**

Closes: #398

**Checklist**

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Review by MuratUrsavas — APPROVED** [review]

**Comment by shawaj** [comment]
Here is what it looks like in the various states:


Screenshot_20230115_225719_Chrome
Screenshot_20230115_225800_Chrome
Screenshot_20230115_225819_Chrome

**Comment by shawaj** [comment]
You happy with this @KevinWassermann94 ?

**Comment by KevinWassermann94** [comment]
LGTM!

**Comment by shawaj** [comment]
Great 👍

**Pull request merged**
