### PR TITLE
structure updates + previe html file for UI updates

### PR DESCRIPTION
**Pull request by vladimirpoleshko**
To #61 

Here is an updated page for diagnostic, preview HTML file for now.

Screens:

Desktop:
image

Tablet:
image

image

Mobile:
image

### CODE REVIEW

**Comment by vpetersson** [comment]
Great start @vladimirpoleshko. Got some initial feedback for you here:

122562143-6759e000-d04b-11eb-8155-611b19919fba

**Comment by shawaj** [comment]
Not sure if it matters but I think that the LTE detected currently only shows if the model is outdoor.

@ryanteck can you confirm?

Also @vpetersson I wonder if we should change ECC Detected to someone like ECC Security Chip Detected or similar. As most people won't know what ECC means

**Comment by shawaj** [comment]
I guess also we can get the tech support guys to document what everything means as part of the helium.nebra.com guides

**Comment by vpetersson** [comment]
> Not sure if it matters but I think that the LTE detected currently only shows if the model is outdoor.

Yeah we should definitely be able to make this page conditional. 

> I wonder if we should change ECC Detected to someone like ECC Security Chip Detected or similar. As most people won't know what ECC means

Yeah that's a good point.

**Comment by vpetersson** [comment]
> I guess also we can get the tech support guys to document what everything means as part of the https://helium.nebra.com guides

100%. Would be great to have some support links here.

**Comment by ryanteck** [comment]
It already only does show LTE if on an outdoor unit.

**Comment by shawaj** [comment]
@ryanteck yeah I thought so just wanted to double check as that will effect how the blocks are displayed I guess

**Comment by vpetersson** [comment]
@shawaj Yeah this is just the design. We haven't ported over the logic yet.

**Comment by robputt** [comment]
See https://github.com/NebraLtd/hm-diag/pull/6

Also please use JINJA template for rendering the page, the current method isn't very tasty.
- https://jinja2docs.readthedocs.io/en/stable/

**Comment by vpetersson** [comment]
@robputt Yeah. The plan is to use JINJA2. This is just a first draft of the design. It's blocked by #60, which should allow for easy adoption of JINJA2.

**Comment by vpetersson** [comment]
@robputt i take it we can close this one out in favor of #81?

**Comment by robputt** [comment]
> @robputt i take it we can close this one out in favor of #81?

I think so...

**Comment by vpetersson** [comment]
Closing this one out. Good stuff here @vladimirpoleshko.

**Pull request closed without merging**
