### PR TITLE
fix path, remove unavailable key, edit dockerfile, edit nginx conf

### LINKED ISSUE #79: Diagnostics crashing
I deployed master to testnet, and it's now crashing with the following error:

```
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/utils.py", line 122, in writing_data
 diagnostics      with open(path, 'w') as file:
 diagnostics  FileNotFoundError: [Errno 2] No such file or directory: '/opt/nebraDiagnostics/html/diagnostics.json'
 diagnostics  
 diagnostics  During handling of the above exception, another exception occurred:
 diagnostics  
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/main.py", line 254, in <module>
 diagnostics      main()
 diagnostics    File "/opt/main.py", line 245, in main
 diagnostics      write_info_to_files(prod_diagnostics, diagnostics)
 diagnostics    File "/opt/main.py", line 128, in write_info_to_files
 diagnostics      utils.writing_data(path, data)
 diagnostics    File "/opt/utils.py", line 125, in writing_data
 diagnostics      raise FileNotFoundError(
 diagnostics  FileNotFoundError: Directory does not exist in the path: /opt/nebraDiagnostics/html/diagnostics.json
```

I have since reverted the update.

### PR DESCRIPTION
**Pull request by ilyastrodubtsev**
Closes #79

### CODE REVIEW

**Comment by vpetersson** [comment]
Can we do this the other way around instead and change `/opt/nebraDiagnostics` to just `/opt` on the python side?

**Comment by ilyastrodubtsev** [comment]
@vpetersson You mean stop writing all files to a separate folder. And store them simply in the /opt folder

**Comment by vpetersson** [comment]
> @vpetersson You mean stop writing all files to a separate folder. And store them simply in the /opt folder

Yes, exactly. I really see no reason for having it in a subfolder.

**Comment by ilyastrodubtsev** [comment]
@vpetersson I think yes. Now I will make and test it locally.

**Review by vpetersson — APPROVED** [review]

**Pull request merged**
